name: Compile Atmosphere with edited logo

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo dkp-pacman -Sy
        sudo apt-get install -y zip unzip python3-pip
        sudo dkp-pacman -S --noconfirm switch-dev switch-glm switch-libjpeg-turbo hactool devkitARM
        pip3 install lz4 pycryptodome --break-system-packages
        
    - name: Compile all
      run: |
        git config --global --add safe.directory '*'
        make -j$(nproc)

    - name: Extract files
      run: |
        rm out/nintendo_nx_arm64_armv8a/release/*-debug.zip
        unzip -j out/nintendo_nx_arm64_armv8a/release/*.zip atmosphere/package3 -d out/nintendo_nx_arm64_armv8a/release/

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Atmosphere-Custom-Logo
        path: out/nintendo_nx_arm64_armv8a/release
